
<!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="container">
      
      <div class="credits">
        <h5>Contato</h5><br>
       <!-- =======  <p>Telefone: (XX) XXXX-XXXX</p> ======= -->
        <p>Email: Pamella.candeia@edu.ufes.br & thiago@edu.ufes.br</p>
        
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>PhotoFolio</span></strong>. All Rights Reserved
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  

</body>

</html>
